CREATE DATABASE [EJERCICIOS_UTN];
GO
USE [EJERCICIOS_UTN];
GO
CREATE TABLE [EJERCICIOS_UTN].dbo.JUEGOS
    (
    CODIGO_JUEGO INT IDENTITY(1,1) PRIMARY KEY ,
    CODIGO_USUARIO INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL ,
    PRECIO FLOAT NOT NULL,
    GENERO VARCHAR(255) NOT NULL,
    );
GO
Insert into JUEGOS VALUES (1000,'HALO: MCC',1500,'FPS')
GO
CREATE TABLE [EJERCICIOS_UTN].dbo.USUARIOS
    (
    CODIGO_USUARIO INT IDENTITY(1000,1) PRIMARY KEY ,
    EMAIL VARCHAR(255) NOT NULL ,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    );
GO
Insert into USUARIOS VALUES ('lauti@gmail','lgalarza','1234')
Insert into USUARIOS VALUES ('mauricio@gmail','mcerizza','4321')
Insert into USUARIOS VALUES ('esteban@gmail','eprieto','4532')